// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ActiveListeners extends Table {
  public static ActiveListeners getRootAsActiveListeners(ByteBuffer _bb) { return getRootAsActiveListeners(_bb, new ActiveListeners()); }
  public static ActiveListeners getRootAsActiveListeners(ByteBuffer _bb, ActiveListeners obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ActiveListeners __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int activeListeners() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createActiveListeners(FlatBufferBuilder builder,
      int active_listeners) {
    builder.startObject(1);
    ActiveListeners.addActiveListeners(builder, active_listeners);
    return ActiveListeners.endActiveListeners(builder);
  }

  public static void startActiveListeners(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addActiveListeners(FlatBufferBuilder builder, int activeListeners) { builder.addInt(0, activeListeners, 0); }
  public static int endActiveListeners(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

