// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BroadCast extends Table {
  public static BroadCast getRootAsBroadCast(ByteBuffer _bb) { return getRootAsBroadCast(_bb, new BroadCast()); }
  public static BroadCast getRootAsBroadCast(ByteBuffer _bb, BroadCast obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BroadCast __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte encoding() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 1; }

  public static int createBroadCast(FlatBufferBuilder builder,
      byte encoding) {
    builder.startObject(1);
    BroadCast.addEncoding(builder, encoding);
    return BroadCast.endBroadCast(builder);
  }

  public static void startBroadCast(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addEncoding(FlatBufferBuilder builder, byte encoding) { builder.addByte(0, encoding, 1); }
  public static int endBroadCast(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

