// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Comment struct {
	_tab flatbuffers.Table
}

func GetRootAsComment(buf []byte, offset flatbuffers.UOffsetT) *Comment {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Comment{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Comment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Comment) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Comment) UserName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Comment) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CommentStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CommentAddUserName(builder *flatbuffers.Builder, userName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userName), 0)
}
func CommentAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(text), 0)
}
func CommentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
