// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Comment extends Table {
  public static Comment getRootAsComment(ByteBuffer _bb) { return getRootAsComment(_bb, new Comment()); }
  public static Comment getRootAsComment(ByteBuffer _bb, Comment obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Comment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createComment(FlatBufferBuilder builder,
      int user_nameOffset,
      int textOffset) {
    builder.startObject(2);
    Comment.addText(builder, textOffset);
    Comment.addUserName(builder, user_nameOffset);
    return Comment.endComment(builder);
  }

  public static void startComment(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUserName(FlatBufferBuilder builder, int userNameOffset) { builder.addOffset(0, userNameOffset, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static int endComment(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

