// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	InputEncodingOpus = 1
	InputEncodingPCM = 2
	InputEncodingAAC = 3
)

var EnumNamesInputEncoding = map[int]string{
	InputEncodingOpus:"Opus",
	InputEncodingPCM:"PCM",
	InputEncodingAAC:"AAC",
}

