// automatically generated by the FlatBuffers compiler, do not modify

package message;

public final class InputEncoding {
  private InputEncoding() { }
  public static final byte Opus = 1;
  public static final byte PCM = 2;
  public static final byte AAC = 3;

  public static final String[] names = { "Opus", "PCM", "AAC", };

  public static String name(int e) { return names[e - Opus]; }
}

