// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	MessageNONE = 0
	MessageStreamControl = 1
	MessageStreamFrame = 2
	MessageStreamComment = 3
)

var EnumNamesMessage = map[int]string{
	MessageNONE:"NONE",
	MessageStreamControl:"StreamControl",
	MessageStreamFrame:"StreamFrame",
	MessageStreamComment:"StreamComment",
}

