# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

class Message(object):
    NONE = 0
    StreamBroadCast = 1
    StreamPause = 2
    StreamStop = 3
    StreamFrame = 4
    StreamComment = 5
    StreamSubscribe = 6
    StreamResponse = 7

