// automatically generated by the FlatBuffers compiler, do not modify

package message;

public final class Message {
  private Message() { }
  public static final byte NONE = 0;
  public static final byte BroadCast = 1;
  public static final byte Pause = 2;
  public static final byte Stop = 3;
  public static final byte Frame = 4;
  public static final byte Comment = 5;
  public static final byte Subscribe = 6;
  public static final byte Response = 7;
  public static final byte Status = 8;
  public static final byte UnSubscribe = 9;
  public static final byte ActiveListeners = 10;

  public static final String[] names = { "NONE", "BroadCast", "Pause", "Stop", "Frame", "Comment", "Subscribe", "Response", "Status", "UnSubscribe", "ActiveListeners", };

  public static String name(int e) { return names[e]; }
}

