// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	MessageNONE = 0
	MessageStreamBroadCast = 1
	MessageStreamPause = 2
	MessageStreamStop = 3
	MessageStreamFrame = 4
	MessageStreamComment = 5
	MessageStreamSubscribe = 6
	MessageStreamResponse = 7
)

var EnumNamesMessage = map[int]string{
	MessageNONE:"NONE",
	MessageStreamBroadCast:"StreamBroadCast",
	MessageStreamPause:"StreamPause",
	MessageStreamStop:"StreamStop",
	MessageStreamFrame:"StreamFrame",
	MessageStreamComment:"StreamComment",
	MessageStreamSubscribe:"StreamSubscribe",
	MessageStreamResponse:"StreamResponse",
}

