// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	MessageNONE = 0
	MessageBroadCast = 1
	MessagePause = 2
	MessageStop = 3
	MessageFrame = 4
	MessageComment = 5
	MessageSubscribe = 6
	MessageResponse = 7
	MessageStatus = 8
	MessageUnSubscribe = 9
)

var EnumNamesMessage = map[int]string{
	MessageNONE:"NONE",
	MessageBroadCast:"BroadCast",
	MessagePause:"Pause",
	MessageStop:"Stop",
	MessageFrame:"Frame",
	MessageComment:"Comment",
	MessageSubscribe:"Subscribe",
	MessageResponse:"Response",
	MessageStatus:"Status",
	MessageUnSubscribe:"UnSubscribe",
}

