// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Pause struct {
	_tab flatbuffers.Table
}

func GetRootAsPause(buf []byte, offset flatbuffers.UOffsetT) *Pause {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Pause{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Pause) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Pause) Table() flatbuffers.Table {
	return rcv._tab
}

func PauseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PauseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
