// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Pause extends Table {
  public static Pause getRootAsPause(ByteBuffer _bb) { return getRootAsPause(_bb, new Pause()); }
  public static Pause getRootAsPause(ByteBuffer _bb, Pause obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Pause __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startPause(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endPause(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

