// automatically generated by the FlatBuffers compiler, do not modify

package message;

public final class ResponseStatus {
  private ResponseStatus() { }
  public static final byte OK = 1;
  public static final byte NoStream = 2;
  public static final byte NotAllowed = 3;
  public static final byte Error = 4;

  public static final String[] names = { "OK", "NoStream", "NotAllowed", "Error", };

  public static String name(int e) { return names[e - OK]; }
}

