// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	ResponseStatusOK = 1
	ResponseStatusNoStream = 2
	ResponseStatusNotAllowed = 3
	ResponseStatusError = 4
)

var EnumNamesResponseStatus = map[int]string{
	ResponseStatusOK:"OK",
	ResponseStatusNoStream:"NoStream",
	ResponseStatusNotAllowed:"NotAllowed",
	ResponseStatusError:"Error",
}

