// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	RpcStatusOK = 1
	RpcStatusError = 2
)

var EnumNamesRpcStatus = map[int]string{
	RpcStatusOK:"OK",
	RpcStatusError:"Error",
}

