// automatically generated by the FlatBuffers compiler, do not modify

package message;

public final class RpcStatus {
  private RpcStatus() { }
  public static final byte OK = 1;
  public static final byte Error = 2;

  public static final String[] names = { "OK", "Error", };

  public static String name(int e) { return names[e - OK]; }
}

