// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetupStreamRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSetupStreamRequest(buf []byte, offset flatbuffers.UOffsetT) *SetupStreamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetupStreamRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SetupStreamRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetupStreamRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetupStreamRequest) StreamId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SetupStreamRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetupStreamRequestAddStreamId(builder *flatbuffers.Builder, streamId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(streamId), 0)
}
func SetupStreamRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
