// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetupStreamResponse extends Table {
  public static SetupStreamResponse getRootAsSetupStreamResponse(ByteBuffer _bb) { return getRootAsSetupStreamResponse(_bb, new SetupStreamResponse()); }
  public static SetupStreamResponse getRootAsSetupStreamResponse(ByteBuffer _bb, SetupStreamResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SetupStreamResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String streamId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer streamIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public byte status() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 1; }

  public static int createSetupStreamResponse(FlatBufferBuilder builder,
      int stream_idOffset,
      byte status) {
    builder.startObject(2);
    SetupStreamResponse.addStreamId(builder, stream_idOffset);
    SetupStreamResponse.addStatus(builder, status);
    return SetupStreamResponse.endSetupStreamResponse(builder);
  }

  public static void startSetupStreamResponse(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStreamId(FlatBufferBuilder builder, int streamIdOffset) { builder.addOffset(0, streamIdOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(1, status, 1); }
  public static int endSetupStreamResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

