// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetupStreamRequest extends Table {
  public static SetupStreamRequest getRootAsSetupStreamRequest(ByteBuffer _bb) { return getRootAsSetupStreamRequest(_bb, new SetupStreamRequest()); }
  public static SetupStreamRequest getRootAsSetupStreamRequest(ByteBuffer _bb, SetupStreamRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SetupStreamRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String streamId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer streamIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createSetupStreamRequest(FlatBufferBuilder builder,
      int stream_idOffset) {
    builder.startObject(1);
    SetupStreamRequest.addStreamId(builder, stream_idOffset);
    return SetupStreamRequest.endSetupStreamRequest(builder);
  }

  public static void startSetupStreamRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStreamId(FlatBufferBuilder builder, int streamIdOffset) { builder.addOffset(0, streamIdOffset, 0); }
  public static int endSetupStreamRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishSetupStreamRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

