// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Status struct {
	_tab flatbuffers.Table
}

func GetRootAsStatus(buf []byte, offset flatbuffers.UOffsetT) *Status {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Status{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Status) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Status) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Status) Status() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Status) MutateStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *Status) SubscribeCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Status) MutateSubscribeCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func StatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StatusAddStatus(builder *flatbuffers.Builder, status int8) {
	builder.PrependInt8Slot(0, status, 0)
}
func StatusAddSubscribeCount(builder *flatbuffers.Builder, subscribeCount int32) {
	builder.PrependInt32Slot(1, subscribeCount, 0)
}
func StatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
