// automatically generated by the FlatBuffers compiler, do not modify

package message;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Status extends Table {
  public static Status getRootAsStatus(ByteBuffer _bb) { return getRootAsStatus(_bb, new Status()); }
  public static Status getRootAsStatus(ByteBuffer _bb, Status obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Status __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int subscribeCount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createStatus(FlatBufferBuilder builder,
      byte status,
      int subscribe_count) {
    builder.startObject(2);
    Status.addSubscribeCount(builder, subscribe_count);
    Status.addStatus(builder, status);
    return Status.endStatus(builder);
  }

  public static void startStatus(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static void addSubscribeCount(FlatBufferBuilder builder, int subscribeCount) { builder.addInt(1, subscribeCount, 0); }
  public static int endStatus(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

