// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	StatusOK = 1
	StatusNoStream = 2
	StatusNotAllowed = 3
	StatusError = 4
)

var EnumNamesStatus = map[int]string{
	StatusOK:"OK",
	StatusNoStream:"NoStream",
	StatusNotAllowed:"NotAllowed",
	StatusError:"Error",
}

