// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Stop struct {
	_tab flatbuffers.Table
}

func GetRootAsStop(buf []byte, offset flatbuffers.UOffsetT) *Stop {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stop{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Stop) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stop) Table() flatbuffers.Table {
	return rcv._tab
}

func StopStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StopEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
