// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	StreamStatusCREATED = 0
	StreamStatusSTREAMING = 1
	StreamStatusSTOPPED = 2
	StreamStatusERROR = 3
)

var EnumNamesStreamStatus = map[int]string{
	StreamStatusCREATED:"CREATED",
	StreamStatusSTREAMING:"STREAMING",
	StreamStatusSTOPPED:"STOPPED",
	StreamStatusERROR:"ERROR",
}

