// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamUnSubscribe struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamUnSubscribe(buf []byte, offset flatbuffers.UOffsetT) *StreamUnSubscribe {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamUnSubscribe{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamUnSubscribe) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamUnSubscribe) Table() flatbuffers.Table {
	return rcv._tab
}

func StreamUnSubscribeStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StreamUnSubscribeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
