// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	StreamActionBroadCast = 1
	StreamActionPause = 2
	StreamActionStop = 3
)

var EnumNamesStreamAction = map[int]string{
	StreamActionBroadCast:"BroadCast",
	StreamActionPause:"Pause",
	StreamActionStop:"Stop",
}

