# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

import flatbuffers

class StreamResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStreamResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamResponse()
        x.Init(buf, n + offset)
        return x

    # StreamResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StreamResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

def StreamResponseStart(builder): builder.StartObject(1)
def StreamResponseAddStatus(builder, status): builder.PrependInt8Slot(0, status, 1)
def StreamResponseEnd(builder): return builder.EndObject()
