// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStatus(buf []byte, offset flatbuffers.UOffsetT) *StreamStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStatus{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStatus) Status() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func StreamStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamStatusAddStatus(builder *flatbuffers.Builder, status int8) {
	builder.PrependInt8Slot(0, status, 0)
}
func StreamStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
