# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

import flatbuffers

class StreamPause(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStreamPause(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamPause()
        x.Init(buf, n + offset)
        return x

    # StreamPause
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StreamPauseStart(builder): builder.StartObject(0)
def StreamPauseEnd(builder): return builder.EndObject()
