// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamFrame(buf []byte, offset flatbuffers.UOffsetT) *StreamFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamFrame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamFrame) FrameSize() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamFrame) MutateFrameSize(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *StreamFrame) SampleRate() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamFrame) MutateSampleRate(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *StreamFrame) Channels() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamFrame) MutateChannels(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *StreamFrame) Frame(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *StreamFrame) FrameLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamFrame) FrameBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StreamFrameAddFrameSize(builder *flatbuffers.Builder, frameSize byte) {
	builder.PrependByteSlot(0, frameSize, 0)
}
func StreamFrameAddSampleRate(builder *flatbuffers.Builder, sampleRate uint32) {
	builder.PrependUint32Slot(1, sampleRate, 0)
}
func StreamFrameAddChannels(builder *flatbuffers.Builder, channels byte) {
	builder.PrependByteSlot(2, channels, 0)
}
func StreamFrameAddFrame(builder *flatbuffers.Builder, frame flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(frame), 0)
}
func StreamFrameStartFrameVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func StreamFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
