// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamPause struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamPause(buf []byte, offset flatbuffers.UOffsetT) *StreamPause {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamPause{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamPause) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamPause) Table() flatbuffers.Table {
	return rcv._tab
}

func StreamPauseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StreamPauseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
