// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	StreamActionStart = 1
	StreamActionPause = 2
	StreamActionStop = 3
	StreamActionSubscribe = 4
)

var EnumNamesStreamAction = map[int]string{
	StreamActionStart:"Start",
	StreamActionPause:"Pause",
	StreamActionStop:"Stop",
	StreamActionSubscribe:"Subscribe",
}

