// automatically generated by the FlatBuffers compiler, do not modify

package message;

public final class StreamStatus {
  private StreamStatus() { }
  public static final byte CREATED = 0;
  public static final byte STREAMING = 1;
  public static final byte STOPPED = 2;
  public static final byte ERROR = 3;

  public static final String[] names = { "CREATED", "STREAMING", "STOPPED", "ERROR", };

  public static String name(int e) { return names[e]; }
}

