// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamSubscribe struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamSubscribe(buf []byte, offset flatbuffers.UOffsetT) *StreamSubscribe {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamSubscribe{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamSubscribe) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamSubscribe) Table() flatbuffers.Table {
	return rcv._tab
}

func StreamSubscribeStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StreamSubscribeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
