// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamSubscribe struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamSubscribe(buf []byte, offset flatbuffers.UOffsetT) *StreamSubscribe {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamSubscribe{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamSubscribe) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamSubscribe) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamSubscribe) Status() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamSubscribe) MutateStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func StreamSubscribeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamSubscribeAddStatus(builder *flatbuffers.Builder, status int8) {
	builder.PrependInt8Slot(0, status, 0)
}
func StreamSubscribeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
