# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

import flatbuffers

class StreamSubscribe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStreamSubscribe(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamSubscribe()
        x.Init(buf, n + offset)
        return x

    # StreamSubscribe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StreamSubscribeStart(builder): builder.StartObject(0)
def StreamSubscribeEnd(builder): return builder.EndObject()
