// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamStop struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStop(buf []byte, offset flatbuffers.UOffsetT) *StreamStop {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStop{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamStop) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStop) Table() flatbuffers.Table {
	return rcv._tab
}

func StreamStopStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StreamStopEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
