//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: rpc

package message

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for StreamRPC service
type StreamRPCClient interface{
  Setup(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* SetupStreamResponse, error)  
}

type streamRPCClient struct {
  cc *grpc.ClientConn
}

func NewStreamRPCClient(cc *grpc.ClientConn) StreamRPCClient {
  return &streamRPCClient{cc}
}

func (c *streamRPCClient) Setup(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* SetupStreamResponse, error) {
  out := new(SetupStreamResponse)
  err := grpc.Invoke(ctx, "/message.StreamRPC/Setup", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for StreamRPC service
type StreamRPCServer interface {
  Setup(context.Context, *SetupStreamRequest) (*flatbuffers.Builder, error)  
}

func RegisterStreamRPCServer(s *grpc.Server, srv StreamRPCServer) {
  s.RegisterService(&_StreamRPC_serviceDesc, srv)
}

func _StreamRPC_Setup_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SetupStreamRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(StreamRPCServer).Setup(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/message.StreamRPC/Setup",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(StreamRPCServer).Setup(ctx, req.(* SetupStreamRequest))
  }
  return interceptor(ctx, in, info, handler)
}


var _StreamRPC_serviceDesc = grpc.ServiceDesc{
  ServiceName: "message.StreamRPC",
  HandlerType: (*StreamRPCServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Setup",
      Handler: _StreamRPC_Setup_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

