// automatically generated by the FlatBuffers compiler, do not modify

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnSubscribe struct {
	_tab flatbuffers.Table
}

func GetRootAsUnSubscribe(buf []byte, offset flatbuffers.UOffsetT) *UnSubscribe {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnSubscribe{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UnSubscribe) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnSubscribe) Table() flatbuffers.Table {
	return rcv._tab
}

func UnSubscribeStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnSubscribeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
